### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by TheUltimateDuel** [builder-247/node-autotip#22]
Every time i run it after a while it gives this error

C:\Users\Duel\Downloads\Minecraft Programs\node-autotip-master\node_modules\minecraft-protocol\src\transforms\framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read property 'value' of undefined
    at getHoverData (C:\Users\Duel\Downloads\Minecraft Programs\node-autotip-master\index.js:33:34)
    at Bot.onMessage (C:\Users\Duel\Downloads\Minecraft Programs\node-autotip-master\index.js:104:17)
    at Bot.emit (events.js:315:20)
    at Client.<anonymous> (C:\Users\Duel\Downloads\Minecraft Programs\node-autotip-master\node_modules\mineflayer\lib\plugins\chat.js:69:9)
    at Client.emit (events.js:315:20)
    at FullPacketParser.<anonymous> (C:\Users\Duel\Downloads\Minecraft Programs\node-autotip-master\node_modules\minecraft-protocol\src\client.js:87:12)
    at FullPacketParser.emit (events.js:315:20)
    at addChunk (C:\Users\Duel\Downloads\Minecraft Programs\node-autotip-master\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\Duel\Downloads\Minecraft Programs\node-autotip-master\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (C:\Users\Duel\Downloads\Minecraft Programs\node-autotip-master\node_modules\readable-stream\lib\_stream_readable.js:241:10)

**Comment by builder-247** [comment]
Are you running the latest version?

**Comment by TheUltimateDuel** [comment]
> 
> 
> Are you running the latest version?

Yes and i tried a clean install

**Comment by builder-247** [comment]
Can you send your `debug.log` file?

**Comment by TheUltimateDuel** [comment]
[debug.log](https://github.com/builder-247/node-autotip/files/6516013/debug.log)

**Comment by TheUltimateDuel** [comment]
For some reason when I change my language in Hypixel to Pirate it stops crashing for me

**Comment by builder-247** [comment]
> For some reason when I change my language in Hypixel to Pirate it stops crashing for me

What language were you using before?

**Comment by TheUltimateDuel** [comment]
> > For some reason when I change my language in Hypixel to Pirate it stops crashing for me
> 
> 
> 
> What language were you using before?

English

**Comment by builder-247** [comment]
Very interesting. I haven't been able to reproduce this issue.

**Comment by TheUltimateDuel** [comment]
It might have something to do with people on my Friends list but I don't know really

**Comment by Sweatily** [comment]
Having the same issue. 

C:\Users\crush\Desktop\node-autotip-master\node_modules\minecraft-protocol\src\transforms\framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read properties of undefined (reading 'value')
    at getHoverData (C:\Users\crush\Desktop\node-autotip-master\index.js:34:34)
    at EventEmitter.onM
[debug.log](https://github.com/builder-247/node-autotip/files/8375145/debug.log)
essage (C:\Users\crush\Desktop\node-autotip-master\index.js:106:17)
    at EventEmitter.emit (node:events:526:28)
    at Client.<anonymous> (C:\Users\crush\Desktop\node-autotip-master\node_modules\mineflayer\lib\plugins\chat.js:118:9)
    at Client.emit (node:events:526:28)
    at FullPacketParser.<anonymous> (C:\Users\crush\Desktop\node-autotip-master\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (node:events:526:28)
    at addChunk (C:\Users\crush\Desktop\node-autotip-master\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\crush\Desktop\node-autotip-master\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (C:\Users\crush\Desktop\node-autotip-master\node_modules\readable-stream\lib\_stream_readable.js:241:10)

C:\Users\crush\Desktop\node-autotip-master>/
'/' is not recognized as an internal or external command,
operable program or batch file.

**Comment by TheUltimateDuel** [comment]
Hey there I made a small fix that if you would like to merge you can. It just adds a language option so it can change to user preference and in my case fix the problem I had. If you want to check it out i will make a pull request.
