### ISSUE TITLE
Thrown Unhandled Error

### ISSUE THREAD

**Issue by hashdashme** [builder-247/node-autotip#5]
Hi Again,
Recently node-autotip decided to not work. For some reason the script decides to crash around when it's sending the player into limbo.

```bash
> node-autotip@2.1.1 start /home/pi/minecraft/node-autotip
> node index

2019-06-16T07:50:46.686Z game:  Couldn't connect you to that server, so you were put in the SkyBlock lobby!
2019-06-16T07:50:46.945Z info:  You've earned 1057730 Exp, 1185656 Coins and 5934000 Karma using node-autotip
2019-06-16T07:50:47.995Z info:  Sending player to limbo...
2019-06-16T07:51:08.768Z game:                                       
2019-06-16T07:51:08.818Z game:                           
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:779:14)
Emitted 'error' event at:
    at Client.self._client.on (/home/pi/minecraft/node-autotip/node_modules/mineflayer/index.js:93:12)
    at Client.emit (events.js:189:13)
    at Socket.onFatalError (/home/pi/minecraft/node-autotip/node_modules/minecraft-protocol/src/client.js:139:12)
    at Socket.emit (events.js:194:15)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:604:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:781:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-autotip@2.1.1 start: `node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-autotip@2.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-06-16T07_51_09_241Z-debug.log
```

And the full log...
```bash
0 info it worked if it ends with ok
1 verbose cli [ '/home/pi/.nvm/versions/node/v10.15.3/bin/node',
1 verbose cli   '/home/pi/.nvm/versions/node/v10.15.3/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle node-autotip@2.1.1~prestart: node-autotip@2.1.1
6 info lifecycle node-autotip@2.1.1~start: node-autotip@2.1.1
7 verbose lifecycle node-autotip@2.1.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle node-autotip@2.1.1~start: PATH: /home/pi/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/minecraft/node-autotip/node_modules/.bin:/home/pi/.nvm/versions/node/v10.15.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle node-autotip@2.1.1~start: CWD: /home/pi/minecraft/node-autotip
10 silly lifecycle node-autotip@2.1.1~start: Args: [ '-c', 'node index' ]
11 silly lifecycle node-autotip@2.1.1~start: Returned: code: 1  signal: null
12 info lifecycle node-autotip@2.1.1~start: Failed to exec start script
13 verbose stack Error: node-autotip@2.1.1 start: `node index`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/pi/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/pi/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid node-autotip@2.1.1
15 verbose cwd /home/pi/minecraft/node-autotip
16 verbose Linux 4.19.50-v7+
17 verbose argv "/home/pi/.nvm/versions/node/v10.15.3/bin/node" "/home/pi/.nvm/versions/node/v10.15.3/bin/npm" "start"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error node-autotip@2.1.1 start: `node index`
22 error Exit status 1
23 error Failed at the node-autotip@2.1.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Thanks Again in Advance! (:
_I'm still using a Raspberry Pi to run it..._

**Comment by builder-247** [comment]
Thank you for reporting this issue!

Can you show me the debugging output by setting the `NODE_ENV` variable to development in your .env file?

Currently I am unable to deal with errors that occur inside the mineflayer package, but I'm working on using a process manager such as pm2 to do automatic restarts when the errors happen.

**Comment by hashdashme** [comment]
Sure thing!
Here are the results:
```bash
> node-autotip@2.1.1 start /home/pi/minecraft/node-autotip
> node index

2019-06-16T11:57:35.939Z game:  Couldn't connect you to that server, so you were put in the SkyBlock lobby!
2019-06-16T11:57:36.330Z debug:         Logged on mc.hypixel.net:25565
2019-06-16T11:57:36.409Z info:  You've earned 1057730 Exp, 1185656 Coins and 5934000 Karma using node-autotip
2019-06-16T11:57:37.564Z info:  Sending player to limbo...
2019-06-16T11:57:37.576Z debug:         Trying to log in as b9eba427ba6743d8a1002f155b9514ff
2019-06-16T11:57:37.604Z debug:         Server hash is: -3945439dcdee402594966553a60c326482041c0e
2019-06-16T11:57:45.185Z debug:         Successfully created Mojang session!
2019-06-16T11:57:50.454Z debug:         Autotip session: {"success":true,"sessionKey":"LMo3SIgwrSf6vL1cubY6r9LTh0t7uBst","keepAliveRate":300,"tipWaveRate":915,"tipCycleRate":5}
2019-06-16T11:57:52.309Z debug:         Need to tip [{"gamemode":"all"},{"gamemode":"HungerGames","username":"S21P"},{"gamemode":"Battleground","username":"al3alamy_YT"},{"gamemode":"TNTGames","username":"SAnoobGaming"},{"gamemode":"TrueCombat","username":"PapaCarlll"},{"gamemode":"SpeedUHC","username":"JOHNNYHICKMAN"},{"gamemode":"MCGO","username":"TaNguNum"}]
2019-06-16T11:58:10.568Z debug:         /tipall
2019-06-16T11:58:10.574Z debug:         /tip S21P HungerGames
2019-06-16T11:58:10.579Z debug:         /tip al3alamy_YT Battleground
2019-06-16T11:58:10.692Z game:                                       
2019-06-16T11:58:10.740Z game:                           
2019-06-16T11:58:11.009Z game:  [MVP+] hashdash joined the lobby!
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:779:14)
Emitted 'error' event at:
    at Client.self._client.on (/home/pi/minecraft/node-autotip/node_modules/mineflayer/index.js:93:12)
    at Client.emit (events.js:189:13)
    at Socket.onFatalError (/home/pi/minecraft/node-autotip/node_modules/minecraft-protocol/src/client.js:139:12)
    at Socket.emit (events.js:194:15)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:604:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:781:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-autotip@2.1.1 start: `node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-autotip@2.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-06-16T11_58_11_169Z-debug.log
```
And the full log...
```bash
0 info it worked if it ends with ok
1 verbose cli [ '/home/pi/.nvm/versions/node/v10.15.3/bin/node',
1 verbose cli   '/home/pi/.nvm/versions/node/v10.15.3/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle node-autotip@2.1.1~prestart: node-autotip@2.1.1
6 info lifecycle node-autotip@2.1.1~start: node-autotip@2.1.1
7 verbose lifecycle node-autotip@2.1.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle node-autotip@2.1.1~start: PATH: /home/pi/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/minecraft/node-autotip/node_modules/.bin:/home/pi/.nvm/versions/node/v10.15.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle node-autotip@2.1.1~start: CWD: /home/pi/minecraft/node-autotip
10 silly lifecycle node-autotip@2.1.1~start: Args: [ '-c', 'node index' ]
11 silly lifecycle node-autotip@2.1.1~start: Returned: code: 1  signal: null
12 info lifecycle node-autotip@2.1.1~start: Failed to exec start script
13 verbose stack Error: node-autotip@2.1.1 start: `node index`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/pi/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/pi/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid node-autotip@2.1.1
15 verbose cwd /home/pi/minecraft/node-autotip
16 verbose Linux 4.19.50-v7+
17 verbose argv "/home/pi/.nvm/versions/node/v10.15.3/bin/node" "/home/pi/.nvm/versions/node/v10.15.3/bin/npm" "start"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error node-autotip@2.1.1 start: `node index`
22 error Exit status 1
23 error Failed at the node-autotip@2.1.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by hashdashme** [comment]
>  I'm working on using a process manager such as pm2 to do automatic restarts when the errors happen.

I've made a simple python script that relaunches script and pauses when I hop onto Hypixel (resulting it the bot getting kicked..)

**Comment by builder-247** [comment]
That's weird... It's trying to do several tips at the same time. I'm unable to reproduce this after trying with several machines. Does this happen every time?

**Comment by hashdashme** [comment]
> Does this happen every time?

Yep, but sometimes it does not start tipping like this one:

```bash
> node-autotip@2.1.1 start /home/pi/minecraft/node-autotip
> node index

2019-06-17T00:26:10.138Z debug:         Logged on mc.hypixel.net:25565
2019-06-17T00:26:10.263Z info:  You've earned 1057730 Exp, 1185656 Coins and 5934000 Karma using node-autotip
2019-06-17T00:26:11.281Z info:  Sending player to limbo...
2019-06-17T00:26:11.289Z debug:         Trying to log in as b9eba427ba6743d8a1002f155b9514ff
2019-06-17T00:26:11.311Z debug:         Server hash is: -22b7098144d9678e315833cbd1b640df23bd6708
2019-06-17T00:26:15.769Z debug:         Successfully created Mojang session!
2019-06-17T00:26:22.202Z debug:         Autotip session: {"success":true,"sessionKey":"4bHanm8uTvKzaeYFlbbNjtr7KImM70Xc","keepAliveRate":300,"tipWaveRate":915,"tipCycleRate":5}
2019-06-17T00:26:33.015Z debug:         Need to tip [{"gamemode":"all"},{"gamemode":"Battleground","username":"Seydog"},{"gamemode":"MCGO","username":"Coooooo"},{"gamemode":"TrueCombat","username":"Se7en"}]
2019-06-17T00:26:33.089Z game:                                       
2019-06-17T00:26:33.140Z game:                           
2019-06-17T00:26:33.566Z game:  [MVP+] hashdash joined the lobby!
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:779:14)
Emitted 'error' event at:
    at Client.self._client.on (/home/pi/minecraft/node-autotip/node_modules/mineflayer/index.js:93:12)
    at Client.emit (events.js:189:13)
    at Socket.onFatalError (/home/pi/minecraft/node-autotip/node_modules/minecraft-protocol/src/client.js:139:12)
    at Socket.emit (events.js:194:15)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:604:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:781:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-autotip@2.1.1 start: `node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-autotip@2.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-06-17T00_26_33_759Z-debug.log
```

**Comment by builder-247** [comment]
You should try deleting node_modules and running npm install.

**Comment by hashdashme** [comment]
Sadly, that does not fix it...

Same thing...
```bash
> node-autotip@2.1.1 start /home/pi/minecraft/node-autotip
> node index

2019-06-17T12:42:19.662Z game:  Couldn't connect you to that server, so you were put in the SkyBlock lobby!
2019-06-17T12:42:19.749Z debug:         Logged on mc.hypixel.net:25565
2019-06-17T12:42:19.850Z info:  You've earned 1057730 Exp, 1185656 Coins and 5934000 Karma using node-autotip
2019-06-17T12:42:20.947Z info:  Sending player to limbo...
2019-06-17T12:42:20.957Z debug:         Trying to log in as b9eba427ba6743d8a1002f155b9514ff
2019-06-17T12:42:20.981Z debug:         Server hash is: 4beafd6e0b2766d63b1479f1d632d43e1f55a472
2019-06-17T12:42:25.624Z debug:         Successfully created Mojang session!
2019-06-17T12:42:30.835Z debug:         Autotip session: {"success":true,"sessionKey":"pBQh5mlR5l0CCPSg8QbJUm3QRUYVHMov","keepAliveRate":300,"tipWaveRate":915,"tipCycleRate":5}
2019-06-17T12:42:33.701Z debug:         Need to tip [{"gamemode":"all"},{"gamemode":"Battleground","username":"ProjectR"},{"gamemode":"Legacy","username":"Francix200"},{"gamemode":"Arcade","username":"Nepptuu"},{"gamemode":"Walls3","username":"ArenaCloser12"},{"gamemode":"MCGO","username":"Tochno"},{"gamemode":"HungerGames","username":"driat_fr"},{"gamemode":"SpeedUHC","username":"ghoulspit"},{"gamemode":"TrueCombat","username":"TENlS"},{"gamemode":"SkyWars","username":"JoelTiger"},{"gamemode":"TNTGames","username":"Nafizz"}]
2019-06-17T12:42:43.899Z debug:         /tipall
2019-06-17T12:42:43.905Z debug:         /tip ProjectR Battleground
2019-06-17T12:42:43.969Z game:                                       
2019-06-17T12:42:44.041Z game:                           
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:779:14)
Emitted 'error' event at:
    at Client.self._client.on (/home/pi/minecraft/node-autotip/node_modules/mineflayer/index.js:93:12)
    at Client.emit (events.js:189:13)
    at Socket.onFatalError (/home/pi/minecraft/node-autotip/node_modules/minecraft-protocol/src/client.js:139:12)
    at Socket.emit (events.js:194:15)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:604:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:781:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-autotip@2.1.1 start: `node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-autotip@2.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-06-17T12_42_44_473Z-debug.log
```

**Comment by hashdashme** [comment]
I found out that it only crashes if I just played Skyblock.... weird

But works when I disconnect in another lobby other than prototype....

**Comment by hashdashme** [comment]
Got to do with joining Hypixel after playing Skyblock and minelayer package.....

**Comment by hashdashme** [comment]
I just need to move somewhere else other than Skyblock for the script to work
