### ISSUE TITLE
Suddenly not working anymore: SyntaxError

### ISSUE THREAD

**Issue by RedNicStone** [builder-247/node-autotip#6]
Hi,
I was using node-autotip yesterday for my first time for like 20 mins or so, and today I wanted to let it run for a somewhat longer time. (Its running on a server)
However today it wouldn't let me start it. I tried to move to different lobby and reinstall it completely, but that didn't help it.

I get the same error every time:
```
> node-autotip@2.1.1 start /home/****/****/node-autotip
> node index

events.js:183
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /home/****/****/node-autotip/node_modules/yggdrasil/lib/utils.js:28:23
    at IncomingMessage.<anonymous> (/home/****/****/node-autotip/node_modules/phin/lib/phin.compiled.js:1:2162)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-autotip@2.1.1 start: `node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-autotip@2.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/****/.npm/_logs/2020-01-19*****-debug.log
```

Thanks for your help!

**Comment by builder-247** [comment]
Is is still not working? The error looks like invalid response from the Mojang API to me.

**Comment by RedNicStone** [comment]
Well, now its working again.
That's strange since I could log in with the MC launcher
Maybe I was a bit to quick, sorry for the hassle.
